---
title: "analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# init
rm(list = ls())

library(tidyverse)
library(magrittr)

dirs <- list(train = "./train",
             test = "./test")
```

```{r}
# loading the data
# we are provided with txt data, delimited with \t
# the file consist of header, footer (that start with # character and contains some meta info) 
# and the body which contains the measurements from multiple sensors
# (https://developer.android.com/guide/topics/sensors/sensors_overview)

parse_file <- function(file_name) {
  
  # read meta data
  meta_data <- read_lines(file_name, n_max = 10)
  name_vec <- str_split(list_of_files[1],'/')
  
  meta <- list(
    type,
    site_id,
    floor_id,
    floor_name
    
  )
  
  
  
}



list_of_files <- list.files(path = dirs$train, recursive = TRUE, pattern = "\\.txt$", full.names = TRUE)

str_split(list_of_files[1],'/')

list_of_files[1]






parse_file(list_of_files[1])


df <- read.csv2(list_of_files[1], sep="\t", header=FALSE, skip=0, stringsAsFactors = FALSE,
          comment.char = "#", col.names = paste0("V", seq_len(9)))




```

